#!/bin/bash
#------------------------------------------------------------------------------#

sudo pacman-key --init

sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com

sudo pacman-key --lsign-key 3056513887B78AEB

sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' --noconfirm

sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm

#----------------------------------------------------------------------------------------#

sudo sed -i 's/^#\[custom]/\[chaotic-aur\]/' /etc/pacman.conf

sudo sed -i "s/^#SigLevel = Optional TrustAll/Include = \/etc\/pacman.d\/chaotic-mirrorlist/" /etc/pacman.conf

#----------------------------------------------------------------------------------------#

sudo pacman -Syyuu --noconfirm

cd ~/

rm -Rf chaotic

